# This file should contain your personal definitions of filepaths/variables/etc.

food_intake_files_path: '../data/intake_files'
mental_state_files_path: '../data/mental_files'
body_comp_files_path: '../data/body_composition_data'
microbiota_files_path: '../data/microbiota_tax_data'