# This file should contain your personal definitions of filepaths/variables/etc.

<<<<<<< HEAD
food_intake_files_path: './data/intake_files'
mental_state_files_path: ''
body_comp_files_path: './data/body_comp'
microbiota_files_path: ''
=======
food_intake_files_path: '../data/intake_files'
mental_state_files_path: '../data/mental_files'
body_comp_files_path: '../data/body_composition_data'
microbiota_files_path: '../data/microbiota_tax_data'
>>>>>>> 626f8015dff8a729e36929272d63c9b333bca1a6
