# This file should contain your personal definitions of filepaths/variables/etc.

food_intake_files_path: '../data/intake_files'
mental_state_files_path: '../data/mental_files'
body_comp_files_path: '../data/body_composition_data'
microbiota_files_path: '../data/microbiota_tax_data'
complete_blast_output: '../data/complete_blast'
moulded_merged_blast_output: '../data/merged_blast.txt'
taxa_profiles: '../data/subjects_taxa_profile.txt'
blast_taxa_file: '../data/taxa_counts_per_subject.txt'
microbiota_files_path: '../data/microbiota_tax_data'


